# Main configuration file for AI News Ignite
# You can add more sections for other services as needed


gpt_model:
  name: "gpt-4.1"
  temperature: 0.2

openai_search_tools:
  type: web_search_preview
  search_context_size: medium
  model: gpt-4.1

